// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA98DWxO2rR71ehj8ssDZAZySHovSN1-oI',
    appId: '1:1046169935737:web:9489f476ab9f866bc359a8',
    messagingSenderId: '1046169935737',
    projectId: 'voisbe',
    authDomain: 'voisbe.firebaseapp.com',
    storageBucket: 'voisbe.appspot.com',
    measurementId: 'G-MZHE4VP79H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWDMw3aDPhafOGwpJnoiedUDMAZlLU6Lg',
    appId: '1:1046169935737:android:05e71e068d4f73c2c359a8',
    messagingSenderId: '1046169935737',
    projectId: 'voisbe',
    storageBucket: 'voisbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAXVXdDqhHkzHLgI0BLblJ7a_yJ3xpzlY',
    appId: '1:1046169935737:ios:bef63bcb5f5ebcdfc359a8',
    messagingSenderId: '1046169935737',
    projectId: 'voisbe',
    storageBucket: 'voisbe.appspot.com',
    iosBundleId: 'com.app.socialNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAXVXdDqhHkzHLgI0BLblJ7a_yJ3xpzlY',
    appId: '1:1046169935737:ios:1aebc8771eaed8dec359a8',
    messagingSenderId: '1046169935737',
    projectId: 'voisbe',
    storageBucket: 'voisbe.appspot.com',
    iosBundleId: 'com.app.socialNotes.RunnerTests',
  );
}
